const CompanyType = {
  HOUSE_ADVERTISER: 'HOUSE_ADVERTISER',
  HOUSE_AGENCY: 'HOUSE_AGENCY',
  ADVERTISER: 'ADVERTISER',
  AGENCY: 'AGENCY',
  AD_NETWORK: 'AD_NETWORK',
  AFFILIATE_DISTRIBUTION_PARTNER: 'AFFILIATE_DISTRIBUTION_PARTNER',
  CONTENT_PARTNER: 'CONTENT_PARTNER',
  UNKNOWN: 'UNKNOWN'
};

export default CompanyType;
